const STATUS_OK = 200;
const STATUS_CREATED = 201;
const STATUS_NOT_MODIFIED = 304;
const STATUS_BAD_REQUEST = 400;
const STATUS_NOT_FOUND = 404;
const STATUS_INTERNAL_SERVER_ERROR = 500;
const VERBOSE_STATUSES = {
  200: "Ok",
  201: "Created",
  304: "Not Modified",
  400: "Bad Request",
  404: "Not Found",
  500: "Internal Server Error"
}
const API_IP = 'localhost';
const API_PORT = 8505;
const BANNER_DURATION = 10000; // in millis.
const CHAT_BUBBLE_DELAY = 700;
const QUEUE_BACKEND_ADDR = "http://localhost:8510" // 'http://localhost:8510';

export const HTTP_STATUS = {
  STATUS_OK,
  STATUS_CREATED,
  STATUS_NOT_MODIFIED,
  STATUS_BAD_REQUEST,
  STATUS_NOT_FOUND,
  STATUS_INTERNAL_SERVER_ERROR
};

export {
  STATUS_OK,
  STATUS_CREATED,
  STATUS_NOT_MODIFIED,
  STATUS_BAD_REQUEST,
  STATUS_NOT_FOUND,
  STATUS_INTERNAL_SERVER_ERROR,
  API_IP,
  API_PORT,
  BANNER_DURATION,
  CHAT_BUBBLE_DELAY,
  VERBOSE_STATUSES,
  QUEUE_BACKEND_ADDR
};
